INPUT_FULL_PATH = "files/input.txt"
OUTPUT_FULL_PATH = "files/output.txt"
STAGING_PATH = "staging_area/"
IMAGE_PATH = "C:\\Users\\berna\\AppData\\Roaming\\Anki2\\User 1\\collection.media\\"
BACKUP_PATH = "files/backup/"
IPA_DICTIONARY_FULL_PATH = "ipa/fr_FR.txt"
IMAGE_HEIGHT = 300
MAXIMUM_BEGINNING_CHARACTERS_IMAGE_FILENAME = 8
IMAGE_FILENAME_PREFIX = "_FR_"